# NUMPY( Numeric Python Library)
## Difference btn lists and arrays
- Arrays take up less space than lists
- Work faster than lists
- Have more functions than lists

- memory is the amount of processing power needed to perform the functions
- storage is the space where something can be stored

## Diff btn numpy arrays and python lists
- use fixed types while python lists use mixed types
- no type checking while pylists have type checking
- utilize contiguous memory

In [3]:
import numpy as np
#always import numpy library as np

In [7]:
a= np.array([1,2,3])
print(a)

[1 2 3]


**We can have multidimensional arrays and this is an example of one**

In [11]:
two_d= np.array([[1,2],[3,4]])
print(two_d)

[[1 2]
 [3 4]]


**The next one is a 3D array**

In [16]:
three_d= np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(three_d)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


**shape** shows in rows,columns for the array

In [17]:
a.shape

(3,)

In [18]:
two_d.shape

(2, 2)

In [19]:
three_d.shape

(3, 2, 2)

**dtype** shows the type of data in the array

In [20]:
a.dtype

dtype('int32')

In [28]:
x= np.array([1,2,3])
print(x)
y= np.array([5,6,7])
print(y)

[1 2 3]
[5 6 7]


In [24]:
x.dtype

dtype('int32')

In [29]:
y.dtype

dtype('int32')

**arange** returns evenly spaced values within a given interval

In [33]:
c= np.arange(0,100,4)
c

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88, 92, 96])

**reshape** returns an array with the same data but w a new shape

In [35]:
c= c.reshape(5,5)
c

array([[ 0,  4,  8, 12, 16],
       [20, 24, 28, 32, 36],
       [40, 44, 48, 52, 56],
       [60, 64, 68, 72, 76],
       [80, 84, 88, 92, 96]])

In [37]:
x= np.array([1,2,3,4,5,6,7,8,9,10])
x.resize(5,2)
x

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [38]:
x.resize(2,5)
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [40]:
np.ones((1,2),dtype=int)

array([[1, 1]])

In [39]:
np.zeros((2,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

**np.eye** brings the 

In [42]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**linspace** returns evenly spaced numbers over a specified interval

In [49]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [53]:
rand= np.random.randint(41,50,(2,5))
rand

array([[43, 43, 42, 48, 49],
       [42, 41, 44, 44, 49]])

In [54]:
rand.sort()
rand

array([[42, 43, 43, 48, 49],
       [41, 42, 44, 44, 49]])

# **Accessing specific elements, rows etc(indexing and slicing)**


**1D arrays**

In [5]:
one_d= np.arange(13)**2
one_d

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
      dtype=int32)

In [57]:
one_d[5], one_d[7]

(25, 49)

**Use : to indicate range
array(startindex:stopindex)**

In [7]:
one_d[:5]

array([ 0,  1,  4,  9, 16], dtype=int32)

In [9]:
one_d[-3:]

array([100, 121, 144], dtype=int32)

In [12]:
one_d[-1:-5:-1]

array([144, 121, 100,  81], dtype=int32)

**A second ':' can be used to show the step size**

In [6]:
one_d[1:8:2]

array([ 1,  9, 25, 49], dtype=int32)

**2D arrays**

In [13]:
d= np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(d)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [14]:
d[1,2]

10

In [15]:
d[0]

array([1, 2, 3, 4, 5, 6, 7])

In [16]:
d[0,0:6]

array([1, 2, 3, 4, 5, 6])

In [17]:
d[0,0:4:2]

array([1, 3])

In [18]:
d[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [22]:
d[0,-1:-8:-1]

array([7, 6, 5, 4, 3, 2, 1])

#### To access a specific column

In [24]:
d[:,3]

array([ 4, 11])

In [26]:
d[0:2,3]

array([ 4, 11])

#### Changing elements

In [29]:
d[1,2]=200
d

array([[  1,   2,   3,   4,   5,   6,   7],
       [  8,   9, 200,  11,  12,  13,  14]])

#### Changing an entire column

In [32]:
d[:,2]= [100,63]
d

array([[  2,   3, 100,   5,   6,   7,   8],
       [  8,   9,  63,  11,  12,  13,  14]])

## Operations

In [35]:
x= np.array([1,2,3])
y= np.array([4,5,6])
print(x,y)

[1 2 3] [4 5 6]


### Addition

In [44]:
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x**2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


In [37]:
x1= [1,2,3]
y1= [4,5,6]
print(x1+y1)
# that is why we prefer numpy arrays since you can add each element individually

[1, 2, 3, 4, 5, 6]


## Dot product 

Like multiplying matrices

In [45]:
x.dot(y)

32

### Math functions

In [46]:
n= np.array([-4,-2,1,3,5])
n

array([-4, -2,  1,  3,  5])

#### Syntax n.function()

In [47]:
n.sum()

3

In [48]:
n.max()

5

In [49]:
n.mean()

0.6

In [50]:
n.std()

3.2619012860600183

**argmax** and **argmin** returns the index of the maximum or minimum value in the array

In [54]:
n.argmax()

4

In [53]:
n.argmin()

0

In [55]:
test= np.random.randint(0,9,(4,3))
test

array([[1, 7, 8],
       [0, 7, 4],
       [8, 6, 5],
       [7, 7, 1]])

In [56]:
for row in test:
    print(row)
    

[1 7 8]
[0 7 4]
[8 6 5]
[7 7 1]


In [57]:
for i in range(len(test)):
    print(test[3])

[7 7 1]
[7 7 1]
[7 7 1]
[7 7 1]


## Class Exercise

In [60]:
ls_weight_lb=[120,239,100,400,190]
print(ls_weight_lb)

[120, 239, 100, 400, 190]


In [61]:
np_weight_lb= np.array(ls_weight_lb)
np_weight_lb

array([120, 239, 100, 400, 190])

In [66]:
np_weight_kg= np.array(np_weight_lb.dot(0.453592))
print(np_weight_kg)

[ 54.43104  108.408488  45.3592   181.4368    86.18248 ]


In [68]:
ls_height=[1.2,2,2.1,1.5,1.7]
print(ls_height)

[1.2, 2, 2.1, 1.5, 1.7]


In [69]:
np_height= np.array(ls_height)
print(np_height)

[1.2 2.  2.1 1.5 1.7]


In [70]:
np_bmi= np.array(np_weight_kg/(np_height**2))
print(np_bmi)

[37.79933333 27.102122   10.28553288 80.63857778 29.82092734]
