In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [2]:
data= pd.read_csv("1.01. Simple linear regression.csv")
data.head(5)

SAT   GPA
0  1714  2.40
1  1664  2.52
2  1760  2.54
3  1685  2.74
4  1693  2.83

In [3]:
y= data['GPA']
x= data['SAT']

In [4]:
x.shape

(84,)

In [5]:
y.shape

(84,)

In [6]:
# Since they are 1D arrays we need to reshape the feature 
x_matrix= x.values.reshape(-1,1)

In [7]:
x_matrix.shape

(84, 1)

## Regression itself

In [8]:
reg= LinearRegression()

In [9]:
reg.fit(x_matrix,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

## R squared

In [10]:
reg.score(x_matrix,y)

0.40600391479679765

## Coefficients

In [11]:
reg.coef_

array([0.00165569])

## Intercepts

In [12]:
reg.intercept_

0.2750402996602803

## Making predictions

In [13]:
new_array= np.array(1740).reshape(-1,1)
reg.predict(new_array)

array([3.15593751])

## Multiple linear regression

In [14]:
mdata= pd.read_csv('1.02. Multiple linear regression.csv')
mdata

SAT   GPA  Rand 1,2,3
0   1714  2.40           1
1   1664  2.52           3
2   1760  2.54           3
3   1685  2.74           3
4   1693  2.83           2
..   ...   ...         ...
79  1936  3.71           3
80  1810  3.71           1
81  1987  3.73           3
82  1962  3.76           1
83  2050  3.81           2

[84 rows x 3 columns]

In [15]:
x= mdata[['SAT','Rand 1,2,3']]
y= mdata['GPA']

In [16]:
reg.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [17]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [18]:
reg.intercept_

0.29603261264909486

In [19]:
reg.score(x,y)

0.4066811952814285

$R^2_(adj.)=1-(1-R^2)*\frac{n-1}{n-p-1}$

In [20]:
n= x.shape[0]
p= x.shape[1]
r2= reg.score(x,y)

adjusted_r2= 1-(1-r2)*(n-1)/(n-p-1)
adjusted_r2

0.39203134825134023

### Feature selection(F-regression)

- creates a simple linear regression between each feature and the dependent variable

In [21]:
from sklearn.feature_selection import f_regression

In [22]:
f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [23]:
pvalues= f_regression(x,y)[1]
pvalues

array([7.19951844e-11, 6.76291372e-01])

In [24]:
pvalues.round(3)

array([0.   , 0.676])

### Creating a summary table

In [25]:
#reg_summary= pd.DataFrame(data=['SAT','Rand 1,2,3'], columns=['Features'])
reg_summary= pd.DataFrame(data=x.columns.values, columns=['Features'])
reg_summary

Features
0         SAT
1  Rand 1,2,3

In [26]:
reg_summary['Coefficients']= reg.coef_
reg_summary['p-values']= pvalues.round(3)
reg_summary

Features  Coefficients  p-values
0         SAT      0.001654     0.000
1  Rand 1,2,3     -0.008270     0.676

### Feature Scaling/ Standardization

In [27]:
from sklearn.preprocessing import StandardScaler

In [28]:
scaler= StandardScaler()

In [29]:
scaler.fit(x)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [30]:
x_scaled= scaler.transform(x)
# transforms the unscaled inputs

In [31]:
x_scaled

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

### Regression with scaled features

In [32]:
reg= LinearRegression()

In [33]:
reg.fit(x_scaled,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [34]:
reg.coef_

array([ 0.17181389, -0.00703007])

In [35]:
reg.intercept_

3.330238095238095

### Summary table

In [36]:
reg_summary= pd.DataFrame([['Bias'],['SAT'],['Rand 1,2,3']], columns=['Features'])
# bias=intercept
reg_summary['Weights']= reg.intercept_, reg.coef_[0], reg.coef_[1]
reg_summary

Features   Weights
0        Bias  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030

### *Making predictions using weights

In [37]:
new_data= pd.DataFrame(data=[[1750,2],[1850,1]], columns=['SAT','Rand 1,2,3'])
new_data

SAT  Rand 1,2,3
0  1750           2
1  1850           1

In [38]:
reg.predict(new_data)

array([303.99049026, 321.17890961])

In [39]:
scaler.fit(new_data)
new_data_scaled= scaler.transform(new_data)
new_data_scaled

array([[-1.,  1.],
       [ 1., -1.]])

In [40]:
reg.predict(new_data_scaled)

array([3.15139414, 3.50908205])

In [41]:
new_data3= pd.DataFrame(data=[[1700,2],[1800,1]], columns=['SAT','Rand 1,2,3'])
new_data3

SAT  Rand 1,2,3
0  1700           2
1  1800           1

In [43]:
#scaler.fit(new_data2)
new= scaler.transform(new_data3)
new

array([[-2.,  1.],
       [ 0., -1.]])

In [44]:
reg.predict(new)

array([2.97958024, 3.33726816])

### What if Rand 1,2,3 is removed

In [45]:
reg_simple= LinearRegression()
x_simple_matrix= x_scaled[:,0].reshape(-1,1)
reg_simple.fit(x_simple_matrix,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [46]:
reg_simple.predict(new_data_scaled[:,0].reshape(-1,1))

array([3.15820119, 3.502275  ])